title:            Inga's Books
description:      Publisher of Sophie Ma's Magical Glasses

twitter:          ingasbooks
facebook:         ingasbooks

#Comment out url when working locally to resolve base urls correctly
url:              http://whaleen.github.io/ingasbooks.com/

signoff:          # Inga Gelford.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.

links:
  - name:         Home
    url:          /
  - name:         Blog
    url:          /blog
  - name:         Contact
    url:          /contact

pygments:   false
permalink:   /:categories/:title

markdown:         maruku
rdiscount:
  extensions:     [smart]