title:            Inga's Books
description:      Publisher of Sophie Ma's Magical Glasses

twitter:          ingasbooks
facebook:         ingasbooks

facebook_appid:   207386912749291



baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whaleen.github.io/ingas-books/" # the base hostname & protocol for your site


signoff:          # Inga Gelford.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )

# appid for like button in /_includes/share.html
facebook_appid:   207386912749291

links:
  - name:         Home
    url:          /
  - name:         Blog
    url:          /blog
  - name:         Contact
    url:          /contact

pygments:   false
permalink:   /:categories/:title

markdown:         maruku
rdiscount:
  extensions:     [smart]
